services:
  migration:
    build: .
    command: ["alembic", "upgrade", "head"]
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"

  app:
    build: .
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      migration:
        condition: service_completed_successfully
    restart: unless-stopped
    command:
      [
        "uvicorn",
        "app.main:app",
        "--host",
        "0.0.0.0",
        "--port",
        "8000",
        "--log-level",
        "info"
      ]